name: Veracode Fix (Batch)

on:
    push:
        branches:
            - 'feature'

jobs:

    build:
        name: Project Build (Packaging)
        runs-on: ubuntu-latest
        steps:

            # Checks-out the repo under $GITHUB_WORKSPACE
            - name: Checking Out Code Repo
              uses: actions/checkout@v3

            # Download Veracode CLI and build (package) the project
            - name: Downloading Veracode CLI (Latest Version)
              env:
                VID: ${{ SECRETS.VID }}
                VKEY: ${{ SECRETS.VKEY }}
              run: |
                echo '[INFO] --- Downloading Veracode CLI (Latest Version)...'
                curl -fsS https://tools.veracode.com/veracode-cli/install | sh
                export VERACODE_API_KEY_ID=$VID
                export VERACODE_API_KEY_SECRET=$VKEY
                echo ''
                echo '[INFO] --- Packaging project with Veracode Autopackage...'
                ./veracode package -s . -o ./verascan --trust
                ls ./verascan  
                
            # Publishes artifact to be scanned
            - uses: actions/upload-artifact@v4
              with:
                name: veracode-auto-pack-verademo-javascript-api_GH-Actions-js.zip
                path: ./verascan/veracode-auto-pack-verademo-javascript-api_GH-Actions-js.zip

    SAST_pipeline_scan:
        name: Veracode SAST (Pipeline Scan)
        needs: build
        runs-on: ubuntu-latest
        steps:

            # Checks-out the repo under $GITHUB_WORKSPACE
            - name: Checking Out Code Repo
              uses: actions/checkout@v3

            # Gets published artifact to be scanned
            - name: Getting artifact
              uses: actions/download-artifact@v4
              with:
                name: veracode-auto-pack-verademo-javascript-api_GH-Actions-js.zip

            # Executes Veracode Pipeline Scan (SAST)
            - name: Veracode Pipeline Scan
              id: pipeline-scan
              uses: veracode/veracode-pipeline-scan-action@v1.0.21
              with:
                vid: ${{ SECRETS.VID }}
                vkey: ${{ SECRETS.VKEY }}
                file: "veracode-auto-pack-verademo-javascript-api_GH-Actions-js.zip" 
                #veracode_policy_name: "Veracode_Recommended_Very High_+_SCA_-_MPT"
                esd: true
                debug: 0
                fail_build: false

            - uses: actions/upload-artifact@v4
              with:
                name: Veracode Pipeline-Scan Results
                path: results.json 

    veracode-fix:
        name: Veracode Fix
        needs: SAST_pipeline_scan
        runs-on: ubuntu-latest
        steps:

            # Checks-out the repo under $GITHUB_WORKSPACE
            - name: checkout repo
              uses: actions/checkout@v3

            # Gets published results.json file from pipeline scan
            - name: get flaw file
              uses: actions/download-artifact@v4
              with:
                name: Veracode Pipeline-Scan Results
          
            # Creates fixes from static findings
            - name: Create fixes from static findings
              id: convert
              uses: Veracode/veracode-fix@main
              with:
                inputFile: results.json
                vid: ${{ SECRETS.VID }}
                vkey: ${{ SECRETS.VKEY }}
                source_base_path_1: "com/:src/main/java/com/"
                source_base_path_2: "WEB-INF:src/main/webapp/WEB-INF"
                language: javascript
                prComment: true
                fixType: batch
                createPR: true